### ISSUE TITLE
unable to access 'https://github.com/hnginterns/getting-started-h2-2017.git/'

### ISSUE THREAD

**Issue by hdJerry** [hnginterns/getting-started-h2-2017#60]
unable to access 'https://github.com/hnginterns/getting-started-h2-2017.git/

**Comment by johnotu** [comment]
Can you give more details so your issue can be more understood or possibly replicated? For example, what exact error messages were returned, etc.

Between, if you've not been added to the `hnginterns` organisation, you may not have access. Post your email and/or Github username on the Slack channels and mention any of @okoyecb @trojan @arinzedroid @daniella or @aniekanoffiong so you can be added.

**Comment by emyguz** [comment]
I'm accessing GitHub thru mobile... How do I edit the contributor. Text file?

**Comment by johnotu** [comment]
It'll be hard but you can do it by tapping Edit, adding your details and committing it back to the repo.
The #help channel on Slack is the best place you can get help with anything. I strongly advise you use it rather than here.

**Comment by hdJerry** [comment]
Thank you, I appreciate                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: John OtuSent: Saturday, 19 August 2017 14:43To: hnginterns/getting-started-h2-2017Reply To: hnginterns/getting-started-h2-2017Cc: hogan jerry; AuthorSubject: Re: [hnginterns/getting-started-h2-2017] unable to access 'https://github.com/hnginterns/getting-started-h2-2017.git/' (#60)It'll be hard but you can do it by tapping Edit, adding your details and committing it back to the repo.
The #help channel on Slack is the best place you can get help with anything. I strongly advise you use it rather than here.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hnginterns/getting-started-h2-2017","title":"hnginterns/getting-started-h2-2017","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hnginterns/getting-started-h2-2017"}},"updates":{"snippets":[{"icon":"PERSON","message":"@johnotu in #60: It'll be hard but you can do it by tapping Edit, adding your details and committing it back to the repo.\r\nThe #help channel on Slack is the best place you can get help with anything. I strongly advise you use it rather than here."}],"action":{"name":"View Issue","url":"https://github.com/hnginterns/getting-started-h2-2017/issues/60#issuecomment-323523962"}}}

**Comment by hdJerry** [comment]
Mobile isn't a cool option                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Gabriel EmyguzSent: Saturday, 19 August 2017 14:09To: hnginterns/getting-started-h2-2017Reply To: hnginterns/getting-started-h2-2017Cc: hogan jerry; AuthorSubject: Re: [hnginterns/getting-started-h2-2017] unable to access 'https://github.com/hnginterns/getting-started-h2-2017.git/' (#60)I'm accessing GitHub thru mobile... How do I edit the contributor. Text file?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/hnginterns/getting-started-h2-2017","title":"hnginterns/getting-started-h2-2017","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/hnginterns/getting-started-h2-2017"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emyguz in #60: I'm accessing GitHub thru mobile... How do I edit the contributor. Text file?"}],"action":{"name":"View Issue","url":"https://github.com/hnginterns/getting-started-h2-2017/issues/60#issuecomment-323522250"}}}
